FROM python:3.7.3 as dev
WORKDIR /app
COPY . .
RUN pip install cython==0.28.5
RUN python compile.py build_ext --inplace

FROM python:3.7.3-slim as prod
WORKDIR /app
COPY factors_flask.py requirements.txt /app/
COPY --from=dev /app/factors.cpython-37m-x86_64-linux-gnu.so /app
RUN pip install -r requirements.txt
CMD ["python","factors_flask.py"]
